### ISSUE TITLE
docs: Include screenshot of webui

### ISSUE THREAD

**Issue by adamdecaf** [kadaan/promutil#1]
I was looking for a screenshot to preview the webui. It seems handy so I was trying it out. Feel free to include this in the docs.

![Screen Shot 2022-09-02 at 10 23 32 AM](https://user-images.githubusercontent.com/120951/188182328-0aae52fb-b862-4bc0-9153-6dc68fa0c8fc.png)

**Comment by kadaan** [comment]
@adamdecaf Thanks. Hope this is working for you!
